-- SELECT ALL DATA WITHIN THE CUSTOMERS TABLE
SELECT *  FROM customer;

-- SELECT ALL DATA WITHIN THE STORES TABLE
SELECT * FROM store;

-- SELECT ALL DATA WITHIN THE FILMS TABLE
SELECT * FROM film;

-- SELECT CUSTOMERS NAMES AND THEIR RESPECTIVE CUSTOMER ID (3 columns only);
SELECT customer_id,  first_name, last_name FROM customer;

-- SELECT ALL ACTORS NAMES THEIR RESPECTIVE ACTOR ID (3 COLUMNS ONLY);
SELECT actor_id, first_name, last_name FROM actor;

-- SELECT ALL DATA WITHIN CUSTOMERS TABLE (specifying schema);
SELECT * FROM sakila.customer;
