-- WHAT ARE THE DIFFERENT RATINGS THAT ARE ASSIGNED TO FILMS?
SELECT DISTINCT rating from sakila.film;

-- WHAT ARE THE DIFFERENT RENTAL RATES THAT ARE APPLIED TO FILMS?
SELECT DISTINCT rental_rate FROM film;

-- ARE THERE FILMS WITHIN EACH RATING AT EACH PRICE LEVEL?
SELECT DISTINCT rating, rental_rate FROM film;
